// Utility functions for the chat extension

// Pin indicator HTML for conversation lists
export const PIN_INDICATOR_HTML =
  '<span class="github-chat-pin-indicator" title="Pinned"><svg viewBox="0 0 24 24" width="12" height="12" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 17v5M5 17h14v-1.76a2 2 0 00-1.11-1.79l-1.78-.9A2 2 0 0115 10.76V6h1a2 2 0 000-4H8a2 2 0 000 4h1v4.76a2 2 0 01-1.11 1.79l-1.78.9A2 2 0 005 15.24V17z"/></svg></span>'

// Escape HTML to prevent XSS
export function escapeHtml(text: string): string {
  const div = document.createElement("div")
  div.textContent = text
  return div.innerHTML
}

// Format message content with markdown-style formatting
// Supports: **bold**, _italic_, `code`, URLs, and newlines
export function formatMessageContent(text: string): string {
  // First escape HTML to prevent XSS
  let formatted = escapeHtml(text)

  // Convert URLs to clickable links (do this before other formatting)
  // Match URLs that start with http://, https://, or www.
  const urlRegex = /(https?:\/\/[^\s<]+|www\.[^\s<]+)/gi
  formatted = formatted.replace(urlRegex, (url) => {
    const href = url.startsWith("www.") ? `https://${url}` : url
    return `<a href="${href}" target="_blank" rel="noopener noreferrer" class="github-chat-link">${url}</a>`
  })

  // Match bare domains
  // Comprehensive list of common TLDs
  const tlds = [
    // Generic TLDs
    "com",
    "org",
    "net",
    "edu",
    "gov",
    "mil",
    "int",
    // Popular new TLDs
    "io",
    "dev",
    "app",
    "ai",
    "co",
    "so",
    "me",
    "cc",
    "tv",
    "fm",
    "am",
    "pm",
    "xyz",
    "info",
    "biz",
    "pro",
    "name",
    "mobi",
    "tel",
    "jobs",
    "travel",
    "tech",
    "online",
    "site",
    "website",
    "space",
    "store",
    "shop",
    "blog",
    "cloud",
    "digital",
    "design",
    "studio",
    "agency",
    "media",
    "news",
    "art",
    "music",
    "video",
    "photo",
    "game",
    "games",
    "play",
    "fun",
    "live",
    "life",
    "world",
    "zone",
    "city",
    "town",
    "house",
    "home",
    "work",
    "works",
    "team",
    "group",
    "company",
    "business",
    "inc",
    "ltd",
    "vc",
    "ventures",
    "capital",
    "fund",
    "money",
    "cash",
    "pay",
    "bank",
    "finance",
    "insurance",
    "health",
    "fitness",
    "food",
    "recipes",
    "cafe",
    "bar",
    "restaurant",
    "pizza",
    "beer",
    "wine",
    "coffee",
    "auto",
    "car",
    "cars",
    "bike",
    "taxi",
    "flights",
    "hotel",
    "holidays",
    "social",
    "chat",
    "email",
    "mobile",
    "phone",
    "web",
    "network",
    "host",
    "server",
    "software",
    "systems",
    "solutions",
    "services",
    "support",
    "guide",
    "tips",
    "how",
    "wiki",
    "review",
    "reviews",
    "best",
    "top",
    "one",
    "plus",
    "new",
    "now",
    "today",
    "express",
    "direct",
    "global",
    "international",
    "world",
    "earth",
    "green",
    "eco",
    "bio",
    "organic",
    "academy",
    "school",
    "university",
    "college",
    "institute",
    "training",
    "law",
    "legal",
    "attorney",
    "lawyer",
    "doctor",
    "dentist",
    "clinic",
    "consulting",
    "management",
    "marketing",
    "advertising",
    "promo",
    "sale",
    "sales",
    "deals",
    "discount",
    "coupons",
    "codes",
    "gifts",
    "fashion",
    "style",
    "beauty",
    "hair",
    "makeup",
    "jewelry",
    "watches",
    "shoes",
    "clothing",
    "boutique",
    "luxury",
    "vip",
    "club",
    "events",
    "party",
    "wedding",
    "dating",
    "singles",
    "love",
    "family",
    "kids",
    "baby",
    "pet",
    "pets",
    "dog",
    "cat",
    "vet",
    "garden",
    "flowers",
    "gifts",
    "christmas",
    "easter",
    "black",
    "friday",
    "cyber",
    "monday",
    "lol",
    "wtf",
    "fail",
    "win",
    "cool",
    "sexy",
    "hot",
    "xxx",
    "adult",
    "porn",
    "gg",
    "lc",
    "gl",
    "ly",
    "to",
    "sh",
    "be",
    "is",
    "it",
    "im",
    "ws",
    "la",
    "ms",
    "ac",
    "ad",
    "ae",
    "af",
    "ag",
    "al",
    "ao",
    "aq",
    "ar",
    "as",
    "at",
    "aw",
    "ax",
    // Country TLDs
    "us",
    "uk",
    "ca",
    "de",
    "fr",
    "es",
    "it",
    "pt",
    "nl",
    "be",
    "lu",
    "ch",
    "at",
    "ie",
    "se",
    "no",
    "fi",
    "dk",
    "pl",
    "cz",
    "sk",
    "hu",
    "ro",
    "bg",
    "gr",
    "hr",
    "si",
    "rs",
    "ua",
    "ru",
    "by",
    "lt",
    "lv",
    "ee",
    "md",
    "ge",
    "am",
    "az",
    "kz",
    "tr",
    "il",
    "ae",
    "sa",
    "qa",
    "kw",
    "bh",
    "om",
    "jo",
    "lb",
    "sy",
    "iq",
    "ir",
    "pk",
    "in",
    "bd",
    "lk",
    "np",
    "bt",
    "mm",
    "th",
    "vn",
    "la",
    "kh",
    "my",
    "sg",
    "id",
    "ph",
    "tw",
    "hk",
    "mo",
    "cn",
    "jp",
    "kr",
    "kp",
    "mn",
    "au",
    "nz",
    "fj",
    "pg",
    "sb",
    "vu",
    "nc",
    "pf",
    "ws",
    "to",
    "tv",
    "fm",
    "mh",
    "pw",
    "gu",
    "mp",
    "za",
    "na",
    "bw",
    "zw",
    "mz",
    "mg",
    "mu",
    "re",
    "sc",
    "ke",
    "tz",
    "ug",
    "rw",
    "bi",
    "cd",
    "cg",
    "ga",
    "cm",
    "ng",
    "gh",
    "ci",
    "sn",
    "ml",
    "bf",
    "ne",
    "tg",
    "bj",
    "lr",
    "sl",
    "gn",
    "gw",
    "cv",
    "mr",
    "dz",
    "tn",
    "ly",
    "eg",
    "sd",
    "et",
    "er",
    "dj",
    "so",
    "ao",
    "mw",
    "zm",
    "zw",
    "sz",
    "ls",
    "st",
    "gq",
    "cf",
    "td",
    "mx",
    "gt",
    "bz",
    "sv",
    "hn",
    "ni",
    "cr",
    "pa",
    "cu",
    "jm",
    "ht",
    "do",
    "pr",
    "tt",
    "bb",
    "gd",
    "lc",
    "vc",
    "ag",
    "dm",
    "kn",
    "bs",
    "ky",
    "vg",
    "vi",
    "aw",
    "cw",
    "sx",
    "bq",
    "tc",
    "ai",
    "ms",
    "mf",
    "bl",
    "gp",
    "mq",
    "co",
    "ve",
    "gy",
    "sr",
    "br",
    "ec",
    "pe",
    "bo",
    "py",
    "uy",
    "ar",
    "cl",
    "fk"
  ].join("|")

  const bareDomainRegex = new RegExp(
    `(?<![a-zA-Z0-9@/])([a-zA-Z0-9][-a-zA-Z0-9]*\\.(?:${tlds})(?:\\/[^\\s<]*)?)(?![a-zA-Z0-9])`,
    "gi"
  )
  formatted = formatted.replace(bareDomainRegex, (match, domain) => {
    // Don't double-link URLs we already processed
    if (
      formatted.includes(`href="${domain}"`) ||
      formatted.includes(`href="https://${domain}"`)
    ) {
      return match
    }
    return `<a href="https://${domain}" target="_blank" rel="noopener noreferrer" class="github-chat-link">${domain}</a>`
  })

  // Convert code blocks (must do before bold/italic to avoid conflicts)
  // Match `code` but not inside URLs
  formatted = formatted.replace(
    /`([^`]+)`/g,
    '<code class="github-chat-code">$1</code>'
  )

  // Convert **bold** text
  formatted = formatted.replace(
    /\*\*([^*]+)\*\*/g,
    '<strong class="github-chat-bold">$1</strong>'
  )

  // Convert _italic_ text (but not in URLs with underscores)
  // Only match _ surrounded by spaces or at word boundaries
  formatted = formatted.replace(
    /(?<![a-zA-Z0-9])_([^_]+)_(?![a-zA-Z0-9])/g,
    '<em class="github-chat-italic">$1</em>'
  )

  // Convert newlines to <br>
  formatted = formatted.replace(/\n/g, "<br>")

  return formatted
}

// Format relative time (e.g., "5m", "2h", "3d")
export function formatRelativeTime(timestamp: number): string {
  const now = Date.now()
  const diff = now - timestamp
  const minutes = Math.floor(diff / 60000)
  const hours = Math.floor(diff / 3600000)
  const days = Math.floor(diff / 86400000)

  if (minutes < 1) return "now"
  if (minutes < 60) return `${minutes}m`
  if (hours < 24) return `${hours}h`
  if (days < 7) return `${days}d`
  return new Date(timestamp).toLocaleDateString()
}

// Format timestamp to time string (e.g., "2:30 PM")
export function formatTime(timestamp: number): string {
  const date = new Date(timestamp)
  return date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })
}
